//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoNetProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDetail
    {
        public int Empid { get; set; }
        public string Empname { get; set; }
        public Nullable<int> EmpSalary { get; set; }
    }
}
